name: Build and Deploy Auth-service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -B

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: auth-service.jar
          path: target/*.jar
