name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest  # For Windows containers. Switch to `ubuntu-latest` for Linux.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.12'
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: mvn clean install -B

      # Initialize Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: "docker-container"  # Required for multi-platform builds
          install: true              # Ensures Buildx is installed

      # Verify Docker environment
      - name: Show Docker Info
        run: |
          docker version
          docker buildx version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: windows/amd64  # Use `linux/amd64` if targeting Linux
          push: true
          tags: |
            your-docker-username/app:latest
