name: Build and Deploy Auth Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Linux runner

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.12'
          distribution: 'temurin'

      # Build JAR
      - name: Build JAR with Maven
        run: mvn clean install -B

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            your-docker-username/auth-service:latest
            your-docker-username/auth-service:${{ github.sha }}
